name: goreleaser

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  goreleaser:
    uses: depado/github-actions/.github/workflows/goreleaser.yml@b261fdb774efce96fe9d92ef9243a57e2d953d9a # main
